# Automatically generated by pb2py
# fmt: off
from trezor import utils

if False:
    from typing_extensions import Literal

Bitcoin = 1  # type: Literal[1]
if not utils.BITCOIN_ONLY:
    Bitcoin_like = 2  # type: Literal[2]
    Binance = 3  # type: Literal[3]
    Cardano = 4  # type: Literal[4]
Crypto = 5  # type: Literal[5]
if not utils.BITCOIN_ONLY:
    EOS = 6
    Ethereum = 7
    Lisk = 8
    Monero = 9
    NEM = 10
    Ripple = 11
    Stellar = 12
    Tezos = 13
    U2F = 14
    Ontology = 17
Shamir = 15
ShamirGroups = 16
